export const FACULTY_FILTERS = [
  { id: 'all', label: 'All' },
  { id: 'oral-medicine', label: 'Oral Medicine & Radiology' },
  { id: 'conservative-dentistry', label: 'Conservative Dentistry' },
  { id: 'oral-surgery', label: 'Oral & Maxillofacial Surgery' },
  { id: 'orthodontics', label: 'Orthodontics' },
  { id: 'prosthodontics', label: 'Prosthodontics' },
  { id: 'periodontics', label: 'Periodontics & Implantology' },
  { id: 'pedodontics', label: 'Pedodontics' },
  { id: 'public-health-dentistry', label: 'Public Health Dentistry' },
  { id: 'oral-pathology', label: 'Oral & Maxillofacial Pathology' },
  { id: 'implantology', label: 'Implantology' },
]

export const FACULTY = [
  {
    id: 'meera-krishnan',
    name: 'Dr. Meera Krishnan',
    role: 'Professor & HOD',
    departmentId: 'oral-medicine',
    department: 'Oral Medicine',
    qualification: 'MDS (Oral Medicine & Radiology), PhD',
    experience: '22 years',
    research: 'Oral mucosal oncology pathways; early detection of potentially malignant disorders.',
    email: 'meera.krishnan@apdch.edu.in',
    office: 'Block A, Room 214',
    bio: 'Leads diagnostic clinics with a focus on interdisciplinary oncology referral corridors and UG diagnostic competency.',
    image:
      'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=600&q=80&auto=format&fit=crop',
  },
  {
    id: 'arjun-desai',
    name: 'Dr. Arjun Desai',
    role: 'Associate Professor',
    departmentId: 'oral-medicine',
    department: 'Oral Medicine',
    qualification: 'MDS (Oral Medicine & Radiology)',
    experience: '14 years',
    research: 'Orofacial pain, TMD, and medically complex patient pathways.',
    email: 'arjun.desai@apdch.edu.in',
    office: 'Block A, Room 218',
    bio: 'Designs structured pain clinics and teaches risk stratification for medically compromised patients.',
    image:
      'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=600&q=80&auto=format&fit=crop',
  },
  {
    id: 'suresh-natarajan',
    name: 'Dr. Suresh Natarajan',
    role: 'Professor & HOD',
    departmentId: 'oral-surgery',
    department: 'Oral Surgery',
    qualification: 'MDS (Oral & Maxillofacial Surgery)',
    experience: '25 years',
    research: 'Dentoalveolar surgery outcomes; trauma triage protocols.',
    email: 'suresh.natarajan@apdch.edu.in',
    office: 'OT Complex, Faculty Suite 2',
    bio: 'Oversees surgical lists and emergency pathways with a strong emphasis on sterile excellence and consent culture.',
    image:
      'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=600&q=80&auto=format&fit=crop',
  },
  {
    id: 'priya-menon',
    name: 'Dr. Priya Menon',
    role: 'Associate Professor',
    departmentId: 'oral-surgery',
    department: 'Oral Surgery',
    qualification: 'MDS (Oral & Maxillofacial Surgery)',
    experience: '12 years',
    research: 'Minor oral surgery pedagogy; student competence ladders.',
    email: 'priya.menon@apdch.edu.in',
    office: 'OT Complex, Faculty Suite 4',
    bio: 'Mentors undergraduates through stepwise entrustment in local anaesthesia and exodontia.',
    image:
      'https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=600&q=80&auto=format&fit=crop',
  },
  {
    id: 'anitha-selvan',
    name: 'Dr. Anitha Selvan',
    role: 'Professor & HOD',
    departmentId: 'orthodontics',
    department: 'Orthodontics',
    qualification: 'MDS (Orthodontics), MOrth',
    experience: '20 years',
    research: 'Finishing biomechanics; interdisciplinary smile rehabilitation.',
    email: 'anitha.selvan@apdch.edu.in',
    office: 'Ortho Wing, Cabin 01',
    bio: 'Known for meticulous finishing standards and transparent family counselling throughout treatment.',
    image:
      'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&q=80&auto=format&fit=crop',
  },
  {
    id: 'rohit-kapoor',
    name: 'Dr. Rohit Kapoor',
    role: 'Associate Professor',
    departmentId: 'orthodontics',
    department: 'Orthodontics',
    qualification: 'MDS (Orthodontics)',
    experience: '11 years',
    research: 'Growth modification and dentofacial orthopaedics.',
    email: 'rohit.kapoor@apdch.edu.in',
    office: 'Ortho Wing, Cabin 03',
    bio: 'Guides interceptive cases and teaches cephalometric reasoning with clinical clarity.',
    image:
      'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=600&q=80&auto=format&fit=crop',
  },
  {
    id: 'kavitha-sundaram',
    name: 'Dr. Kavitha Sundaram',
    role: 'Professor & HOD',
    departmentId: 'periodontics',
    department: 'Periodontics',
    qualification: 'MDS (Periodontology)',
    experience: '18 years',
    research: 'Regenerative periodontology; perio–systemic interlinks.',
    email: 'kavitha.sundaram@apdch.edu.in',
    office: 'Perio Clinic, Room P-12',
    bio: 'Builds lifelong maintenance cultures for chronic periodontitis and implant soft-tissue health.',
    image:
      'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=600&q=80&auto=format&fit=crop',
  },
  {
    id: 'divya-banerjee',
    name: 'Dr. Divya Banerjee',
    role: 'Professor & HOD',
    departmentId: 'pedodontics',
    department: 'Pedodontics',
    qualification: 'MDS (Pedodontics & Preventive Dentistry)',
    experience: '16 years',
    research: 'Behaviour guidance; caries risk models in school cohorts.',
    email: 'divya.banerjee@apdch.edu.in',
    office: 'Pediatric Wing, Room C-05',
    bio: 'Designs fear-free first visits and partners with schools for preventive outreach.',
    image:
      'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=600&q=80&auto=format&fit=crop',
  },
  {
    id: 'ramesh-pillai',
    name: 'Dr. Ramesh Pillai',
    role: 'Professor & HOD',
    departmentId: 'prosthodontics',
    department: 'Prosthodontics',
    qualification: 'MDS (Prosthodontics), FICD',
    experience: '24 years',
    research: 'Full mouth rehabilitation; denture satisfaction indices.',
    email: 'ramesh.pillai@apdch.edu.in',
    office: 'Prostho Block, Suite 1',
    bio: 'Leads complex rehabilitations with close laboratory collaboration and facial aesthetic balance.',
    image:
      'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=600&q=80&auto=format&fit=crop',
  },
  {
    id: 'sofie-abraham',
    name: 'Dr. Sofie Abraham',
    role: 'Associate Professor',
    departmentId: 'prosthodontics',
    department: 'Prosthodontics',
    qualification: 'MDS (Prosthodontics)',
    experience: '10 years',
    research: 'Implant prosthetics and digital CAD/CAM workflows.',
    email: 'sofie.abraham@apdch.edu.in',
    office: 'Prostho Block, Suite 3',
    bio: 'Brings digital design fluency to residency teaching and patient try-in protocols.',
    image:
      'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=600&q=80&auto=format&fit=crop',
  },
  {
    id: 'gayathri-mohan',
    name: 'Dr. Gayathri Mohan',
    role: 'Professor & HOD',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry',
    qualification: 'MDS (Conservative Dentistry & Endodontics)',
    experience: '19 years',
    research: 'Micro-endodontics; irrigation science and obturation quality.',
    email: 'gayathri.mohan@apdch.edu.in',
    office: 'Cons & Endo, Room E-07',
    bio: 'Champions tooth preservation, rubber-dam culture, and magnification-assisted endodontics.',
    image:
      'https://images.unsplash.com/photo-1527613426441-4da17471b66d?w=600&q=80&auto=format&fit=crop',
  },
  {
    id: 'nikhil-bose',
    name: 'Dr. Nikhil Bose',
    role: 'Associate Professor',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry',
    qualification: 'MDS (Conservative Dentistry & Endodontics)',
    experience: '9 years',
    research: 'Aesthetic operative dentistry; bonding longevity.',
    email: 'nikhil.bose@apdch.edu.in',
    office: 'Cons & Endo, Room E-09',
    bio: 'Teaches adhesive artistry with biology-first decision making for cusp coverage.',
    image:
      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=600&q=80&auto=format&fit=crop',
  },
  {
    id: 'padma-venkatesh',
    name: 'Dr. Padma Venkatesh',
    role: 'Professor & HOD',
    departmentId: 'oral-pathology',
    department: 'Oral Pathology',
    qualification: 'MDS (Oral Pathology), PhD',
    experience: '21 years',
    research: 'Oral oncology pathology; PMD progression markers.',
    email: 'padma.venkatesh@apdch.edu.in',
    office: 'Pathology Lab, Report Cabin',
    bio: 'Anchors tumour boards with precise histopathology and clear clinician-facing reports.',
    image:
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&q=80&auto=format&fit=crop',
  },
  {
    id: 'manjula-krishnan',
    name: 'Dr. Manjula Krishnan',
    role: 'Professor & HOD',
    departmentId: 'public-health-dentistry',
    department: 'Public Health Dentistry',
    qualification: 'MDS (Public Health Dentistry)',
    experience: '17 years',
    research: 'Community programme design; caries prevalence mapping.',
    email: 'manjula.krishnan@apdch.edu.in',
    office: 'Public Health Unit, Desk 1',
    bio: 'Architects district partnerships and student-led outreach with rigorous field ethics.',
    image:
      'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=600&q=80&auto=format&fit=crop',
  },
  {
    id: 'ajay-pratap',
    name: 'Dr. Ajay Pratap',
    role: 'Associate Professor',
    departmentId: 'public-health-dentistry',
    department: 'Public Health Dentistry',
    qualification: 'MDS (Public Health Dentistry), MPH',
    experience: '8 years',
    research: 'Epidemiology, biostatistics, and behaviour-change trials.',
    email: 'ajay.pratap@apdch.edu.in',
    office: 'Public Health Unit, Desk 3',
    bio: 'Trains students in survey design and clean data storytelling for community impact.',
    image:
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&q=80&auto=format&fit=crop',
  },
]
