export const FACULTY_FILTERS = [
  { id: 'all', label: 'All' },
  { id: 'oral-medicine', label: 'Oral Medicine & Radiology' },
  { id: 'conservative-dentistry', label: 'Conservative Dentistry - Endodontics' },
  { id: 'oral-surgery', label: 'Oral & Maxilofacial Surgery' },
  { id: 'orthodontics', label: 'Orthodontics & Dentofacial Orthopaedics' },
  { id: 'prosthodontics', label: 'Prosthodontics and crown Bridge' },
  { id: 'periodontics', label: 'Periodontics & Implantology' },
  { id: 'pedodontics', label: 'Pedodontics & Preventive Dentistry' },
  { id: 'oral-pathology', label: 'Oral Pathology' },
  { id: 'public-health-dentistry', label: 'Public Health Dentistry' },
]

export const FACULTY = [
  {
    id: 'deivanayagi',
    name: 'Dr. M. Deivanayagi',
    role: 'Vice Principal & HOD',
    departmentId: 'oral-medicine',
    department: 'Oral Medicine & Radiology',
    qualification: 'MDS (Oral Medicine & Radiology)',
    experience: '18 years',
    research: 'Oral mucosal oncology pathways; early detection of potentially malignant disorders.',
    email: 'deivanayagi@apdch.edu.in',
    office: 'Block A, Room 214',
    bio: 'Leads diagnostic clinics with a focus on interdisciplinary oncology referral corridors and UG diagnostic competency.',
    image: '/Dr.-M-DeivanayagiMdsPh.d.png',
  },
  {
    id: 'monisha-r',
    name: 'Dr. Monisha R',
    role: 'Senior Lecturer',
    departmentId: 'oral-medicine',
    department: 'Oral Medicine & Radiology',
    qualification: 'MDS (Oral Medicine & Radiology)',
    experience: '10 years',
    research: 'Maxillofacial radiology, 3D CBCT interpretation, and orofacial pain pathways.',
    email: 'monisha.r@apdch.edu.in',
    office: 'Block A, Room 218',
    bio: 'Teaches CBCT interpretation, digital imaging protocols, and diagnostic radiology in Oral Medicine.',
    image: '/Dr.-R-MonishaMds.png',
  },
  {
    id: 'narmadha-chandran',
    name: 'Dr. Narmadha Chandran',
    role: 'Senior Lecturer',
    departmentId: 'oral-medicine',
    department: 'Oral Medicine & Radiology',
    qualification: 'MDS (Oral Medicine & Radiology)',
    experience: '8 years',
    research: 'Oral lesions diagnostics & advanced maxillofacial imaging.',
    email: 'narmadha.chandran@apdch.edu.in',
    office: 'Block A, Room 220',
    bio: 'Specializes in oral medicine, diagnostic radiology, CBCT imaging, and clinical patient care.',
    image: '/Dr.-NarmadhaChandranMds.png',
  },
  {
    id: 'elamparithi',
    name: 'Dr. B. Elamparithi',
    role: 'Senior Lecturer',
    departmentId: 'oral-medicine',
    department: 'Oral Medicine & Radiology',
    qualification: 'MDS (Oral Medicine & Radiology)',
    experience: '7 years',
    research: 'Maxillofacial radiology & diagnostic stomatology.',
    email: 'elamparithi@apdch.edu.in',
    office: 'Block A, Room 222',
    bio: 'Specializes in oral medicine diagnosis, advanced maxillofacial radiography, and clinical dentistry.',
    image: '/Dr.-B-Elamparithi-Mds.png',
  },
  {
    id: 'sindhuja-t',
    name: 'Dr. T. Sindhuja',
    role: 'Senior Lecturer',
    departmentId: 'oral-medicine',
    department: 'Oral Medicine & Radiology',
    qualification: 'MDS (Oral Medicine & Radiology)',
    experience: '6 years',
    research: 'Diagnostic radiology, CBCT imaging, & oral mucosal lesions.',
    email: 'sindhuja.t@apdch.edu.in',
    office: 'Block A, Room 224',
    bio: 'Specializes in oral medicine & radiology diagnostics, TMJ disorders, and digital radiography.',
    image: '/Dr.-T-Sindhuja-Mds.png',
  },
  {
    id: 'giri',
    name: 'Dr. G V V Giri',
    role: 'Professor & HOD',
    departmentId: 'oral-surgery',
    department: 'Oral & Maxilofacial Surgery',
    qualification: 'MDS (Oral & Maxillofacial Surgery), FICD',
    experience: '24 years',
    research: 'Dentoalveolar & maxillofacial surgery outcomes; trauma triage protocols.',
    email: 'drgiri@apdch.edu.in',
    office: 'OT Complex, Faculty Suite 1',
    bio: 'Oversees surgical lists, trauma triage, emergency pathways, and advanced maxillofacial procedures.',
    image: '/HOD-Giri.jpg',
  },
  {
    id: 'james-antony',
    name: 'Dr. M. James Antony Bhagat',
    role: 'Professor',
    departmentId: 'oral-surgery',
    department: 'Oral & Maxilofacial Surgery',
    qualification: 'MDS (Oral & Maxillofacial Surgery)',
    experience: '16 years',
    research: 'Maxillofacial trauma reconstruction, dentoalveolar surgery, & TMJ arthroplasty.',
    email: 'drjamesantonybhagatm@apdch.edu.in',
    office: 'OT Complex, Faculty Suite 3',
    bio: 'Specializes in maxillofacial trauma, minor oral surgery, surgical extractions, and undergraduate surgical training.',
    image: '/james.png',
  },
  {
    id: 'vijayakumar-jain',
    name: 'Dr. S. Vijayakumar Jain',
    role: 'Reader',
    departmentId: 'oral-surgery',
    department: 'Oral & Maxilofacial Surgery',
    qualification: 'MDS (Oral & Maxillofacial Surgery)',
    experience: '11 years',
    research: 'Maxillofacial trauma, orthognathic surgery, & surgical extractions.',
    email: 'drvijaykumar@apdch.edu.in',
    office: 'OT Complex, Faculty Suite 4',
    bio: 'Specializes in maxillofacial trauma management, minor oral surgical procedures, and clinical instruction.',
    image: '/Dr S Vijayakumar Jain.png',
  },
  {
    id: 'srinivasulu-pabbaraju',
    name: 'Dr. Srinivasulu Pabbaraju',
    role: 'Reader',
    departmentId: 'oral-surgery',
    department: 'Oral & Maxilofacial Surgery',
    qualification: 'MDS (Oral & Maxillofacial Surgery)',
    experience: '10 years',
    research: 'Dentoalveolar surgery, maxillofacial trauma, & minor oral surgical procedures.',
    email: 'drsrinivasulupabbaraju@apdch.edu.in',
    office: 'OT Complex, Faculty Suite 5',
    bio: 'Specializes in minor oral surgery, surgical extractions, trauma triage, and clinical student mentorship.',
    image: '/srini.png',
  },
  {
    id: 'hemnaath-r',
    name: 'Dr. R. Hemnaath',
    role: 'Senior Lecturer',
    departmentId: 'oral-surgery',
    department: 'Oral & Maxilofacial Surgery',
    qualification: 'MDS (Oral & Maxillofacial Surgery)',
    experience: '6 years',
    research: 'Minor oral surgery procedures, surgical extractions, & trauma management.',
    email: 'drhemnaath@apdch.edu.in',
    office: 'OT Complex, Faculty Suite 6',
    bio: 'Specializes in minor oral surgery, exodontia protocols, trauma triage, and clinical student mentorship.',
    image: '/hemanth.png',
  },
  {
    id: 'gajapriya-p',
    name: 'Dr. P. Gajapriya',
    role: 'Senior Lecturer',
    departmentId: 'oral-surgery',
    department: 'Oral & Maxilofacial Surgery',
    qualification: 'MDS (Oral & Maxillofacial Surgery)',
    experience: '5 years',
    research: 'Minor oral surgery, dentoalveolar trauma, & surgical exodontia.',
    email: 'drgajapriya@apdch.edu.in',
    office: 'OT Complex, Faculty Suite 7',
    bio: 'Specializes in minor oral surgical procedures, exodontia protocols, trauma triage, and clinical student mentorship.',
    image: '/Dr P Gajapriya.png',
  },
  {
    id: 'sakthi-s',
    name: 'Dr. S. Sakthi',
    role: 'Senior Lecturer',
    departmentId: 'oral-surgery',
    department: 'Oral & Maxilofacial Surgery',
    qualification: 'MDS (Oral & Maxillofacial Surgery)',
    experience: '5 years',
    research: 'Dentoalveolar surgery, minor oral surgical protocols, & maxillofacial trauma.',
    email: 'drsakthiomfs@apdch.edu.in',
    office: 'OT Complex, Faculty Suite 8',
    bio: 'Specializes in minor oral surgical procedures, exodontia protocols, trauma triage, and clinical student mentorship.',
    image: '/sakthi.png',
  },
  {
    id: 'nalin-kumar',
    name: 'Dr. S. Nalinkumar',
    role: 'Senior Lecturer',
    departmentId: 'oral-surgery',
    department: 'Oral & Maxilofacial Surgery',
    qualification: 'MDS (Oral & Maxillofacial Surgery)',
    experience: '8 years',
    research: 'Dentoalveolar surgery, minor oral surgery, & trauma management.',
    email: 'drnalin@apdch.edu.in',
    office: 'OT Complex, Faculty Suite 9',
    bio: 'Specializes in minor oral surgery, exodontia protocols, trauma triage, and clinical student mentorship.',
    image: '/nalinkumar.png',
  },
  {
    id: 'velmurugan-p',
    name: 'Dr. P. Velmurugan',
    role: 'Senior Lecturer',
    departmentId: 'oral-surgery',
    department: 'Oral & Maxilofacial Surgery',
    qualification: 'MDS (Oral & Maxillofacial Surgery)',
    experience: '6 years',
    research: 'Dentoalveolar surgery, minor oral surgery, & trauma management.',
    email: 'drvelmurugan@apdch.edu.in',
    office: 'OT Complex, Faculty Suite 10',
    bio: 'Specializes in minor oral surgery, exodontia protocols, trauma triage, and clinical student mentorship.',
    image: '/p.velmurugan.png',
  },
  {
    id: 'satheesh-g',
    name: 'Dr. G. Satheesh',
    role: 'Reader',
    departmentId: 'oral-surgery',
    department: 'Oral & Maxilofacial Surgery',
    qualification: 'MDS (Oral & Maxillofacial Surgery)',
    experience: '12 years',
    research: 'Dentoalveolar surgery, minor oral surgery, & trauma management.',
    email: 'drsatheesh@apdch.edu.in',
    office: 'OT Complex, Faculty Suite 11',
    bio: 'Specializes in minor oral surgery, exodontia protocols, trauma triage, and clinical student mentorship.',
    image: '/dr.saathesh.png',
  },
  {
    id: 'mora-sathi-rami-reddy',
    name: 'Dr. Mora Sathi Rami Reddy',
    role: 'Professor & HOD',
    departmentId: 'orthodontics',
    department: 'Orthodontics & Dentofacial Orthopaedics',
    qualification: 'MDS (Orthodontics & Dentofacial Orthopedics)',
    experience: '22 years',
    research: 'Finishing biomechanics; interdisciplinary smile rehabilitation; growth modification.',
    email: 'mora.reddy@apdch.edu.in',
    office: 'Ortho Wing, Cabin 01',
    bio: 'Oversees clinical orthodontics, dentofacial orthopaedics, and residency training in Orthodontics.',
    image: '/mora-apdch.jpg',
  },
  {
    id: 'kuldeep-dmello',
    name: 'Dr. Kuldeep D Mello',
    role: 'Professor',
    departmentId: 'orthodontics',
    department: 'Orthodontics & Dentofacial Orthopaedics',
    qualification: 'MDS (Orthodontics & Dentofacial Orthopedics)',
    experience: '16 years',
    research: 'Clear aligner therapy, interceptive orthodontics, & skeletal growth modification.',
    email: 'drkuldeep@apdch.edu.in',
    office: 'Ortho Wing, Cabin 02',
    bio: 'Specializes in orthodontic biomechanics, dentofacial orthopaedics, fixed appliance therapy, and clear aligner treatment planning.',
    image: '/Dr-Kuldeep-DMello-MDS.png',
  },
  {
    id: 'vijaykumar-v',
    name: 'Dr. V. Vijaykumar',
    role: 'Reader',
    departmentId: 'orthodontics',
    department: 'Orthodontics & Dentofacial Orthopaedics',
    qualification: 'MDS (Orthodontics & Dentofacial Orthopedics)',
    experience: '11 years',
    research: 'Clear aligner therapy, interceptive orthodontics, & skeletal growth modification.',
    email: 'drvijaykumarv@apdch.edu.in',
    office: 'Ortho Wing, Cabin 03',
    bio: 'Specializes in orthodontic treatment, interceptive orthopaedics, fixed appliance therapy, and residency training.',
    image: '/Dr V Vijaykumar.png',
  },
  {
    id: 'mayank-trivedi',
    name: 'Dr. Mayank Trivedi',
    role: 'Reader',
    departmentId: 'orthodontics',
    department: 'Orthodontics & Dentofacial Orthopaedics',
    qualification: 'MDS (Orthodontics & Dentofacial Orthopedics)',
    experience: '10 years',
    research: 'Clear aligner biomechanics, growth modification, & orthodontic retention.',
    email: 'drmayank@apdch.edu.in',
    office: 'Ortho Wing, Cabin 04',
    bio: 'Specializes in orthodontic treatment, interceptive orthopaedics, fixed appliance therapy, and clinical student instruction.',
    image: '/dr.mayank.png',
  },
  {
    id: 'priya-k',
    name: 'Dr. K. Priya',
    role: 'Reader',
    departmentId: 'orthodontics',
    department: 'Orthodontics & Dentofacial Orthopaedics',
    qualification: 'MDS (Orthodontics & Dentofacial Orthopedics)',
    experience: '8 years',
    research: 'Clear aligner biomechanics, growth modification, & orthodontic retention.',
    email: 'drpriyak@apdch.edu.in',
    office: 'Ortho Wing, Cabin 05',
    bio: 'Specializes in orthodontic treatment, interceptive orthopaedics, fixed appliance therapy, and clinical student instruction.',
    image: '/dr.priya.png',
  },
  {
    id: 'santhosh-kumar-v',
    name: 'Dr. V. Santhosh Kumar',
    role: 'Senior Lecturer',
    departmentId: 'orthodontics',
    department: 'Orthodontics & Dentofacial Orthopaedics',
    qualification: 'MDS (Orthodontics & Dentofacial Orthopedics)',
    experience: '5 years',
    research: 'Clear aligner therapy, growth modification, & orthodontic retention.',
    email: 'drsanthosh@apdch.edu.in',
    office: 'Ortho Wing, Cabin 06',
    bio: 'Specializes in orthodontic treatment, interceptive orthopaedics, fixed appliance therapy, and clinical student instruction.',
    image: '/dr.santhosh.png',
  },
  {
    id: 'sruthi-j',
    name: 'Dr. J. Sruthi',
    role: 'Senior Lecturer',
    departmentId: 'orthodontics',
    department: 'Orthodontics & Dentofacial Orthopaedics',
    qualification: 'MDS (Orthodontics & Dentofacial Orthopedics)',
    experience: '5 years',
    research: 'Clear aligner therapy, growth modification, & orthodontic retention.',
    email: 'drsruthi@apdch.edu.in',
    office: 'Ortho Wing, Cabin 07',
    bio: 'Specializes in orthodontic treatment, interceptive orthopaedics, fixed appliance therapy, and clinical student instruction.',
    image: '/sruthi.png',
  },
  {
    id: 'kathijathul-hidhaya-s',
    name: 'Dr. S. Kathijathul Hidhaya',
    role: 'Senior Lecturer',
    departmentId: 'orthodontics',
    department: 'Orthodontics & Dentofacial Orthopaedics',
    qualification: 'MDS (Orthodontics & Dentofacial Orthopedics)',
    experience: '5 years',
    research: 'Clear aligner therapy, growth modification, & orthodontic retention.',
    email: 'drhidhaya@apdch.edu.in',
    office: 'Ortho Wing, Cabin 08',
    bio: 'Specializes in orthodontic treatment, interceptive orthopaedics, fixed appliance therapy, and clinical student instruction.',
    image: '/athijathul Hidhaya.png',
  },
  {
    id: 'thulasidasan-a',
    name: 'Dr. A. Thulasidasan',
    role: 'Senior Lecturer',
    departmentId: 'orthodontics',
    department: 'Orthodontics & Dentofacial Orthopaedics',
    qualification: 'MDS (Orthodontics & Dentofacial Orthopedics)',
    experience: '6 years',
    research: 'Clear aligner therapy, growth modification, & orthodontic retention.',
    email: 'drthulasidasan@apdch.edu.in',
    office: 'Ortho Wing, Cabin 09',
    bio: 'Specializes in orthodontic treatment, interceptive orthopaedics, fixed appliance therapy, and clinical student instruction.',
    image: '/Dr A Thulasidasan.png',
  },
  {
    id: 'subashree-s',
    name: 'Dr. S. Subashree',
    role: 'Senior Lecturer',
    departmentId: 'orthodontics',
    department: 'Orthodontics & Dentofacial Orthopaedics',
    qualification: 'MDS (Orthodontics & Dentofacial Orthopedics)',
    experience: '5 years',
    research: 'Clear aligner therapy, growth modification, & orthodontic retention.',
    email: 'subashree.s@apdch.edu.in',
    office: 'Ortho Wing, Cabin 10',
    bio: 'Specializes in orthodontic treatment, interceptive orthopaedics, fixed appliance therapy, and clinical student instruction.',
    image: '/Dr S Subashree.png',
  },
  {
    id: 'magesh-kumar',
    name: 'Dr. S. Magesh Kumar',
    role: 'Professor & HOD',
    departmentId: 'periodontics',
    department: 'Periodontics & Implantology',
    qualification: 'MDS (Periodontology)',
    experience: '20 years',
    research: 'Regenerative periodontology; perio–systemic interlinks & implant soft-tissue health.',
    email: 'mageshkumar@apdch.edu.in',
    office: 'Perio Clinic, Room P-01',
    bio: 'Leads the Department of Periodontics, guiding advanced periodontal surgical techniques, regeneration, and implantology training.',
    image: '/Magesh-home.jpg',
  },
  {
    id: 'sakshi-madhok',
    name: 'Dr. Sakshi Madhok',
    role: 'Professor & HOD',
    departmentId: 'prosthodontics',
    department: 'Prosthodontics and crown Bridge',
    qualification: 'MDS (Prosthodontics and Crown & Bridge)',
    experience: '18 years',
    research: 'Full mouth rehabilitation, CAD/CAM prosthetics & implant occlusion.',
    email: 'drsakshimadhok@apdch.edu.in',
    office: 'Prostho Block, Suite 1',
    bio: 'Leads clinical prosthodontics, CAD/CAM laboratory workflows, full mouth rehabilitation, and crown & bridge care.',
    image: '/sakshi .jpg',
  },
  {
    id: 'arunkumar-v-r',
    name: 'Dr. V. R. Arunkumar',
    role: 'Professor',
    departmentId: 'prosthodontics',
    department: 'Prosthodontics and crown Bridge',
    qualification: 'MDS (Prosthodontics and Crown & Bridge)',
    experience: '20 years',
    research: 'Full mouth rehabilitation, CAD/CAM prosthetics & implant occlusion.',
    email: 'drarunkumar@apdch.edu.in',
    office: 'Prostho Block, Suite 2',
    bio: 'Specializes in clinical prosthodontics, CAD/CAM laboratory workflows, full mouth rehabilitation, and crown & bridge care.',
    image: '/Dr-V-R-Arunkumar-MDS-2.png',
  },
  {
    id: 'muthuvignesh-j',
    name: 'Dr. J. Muthuvignesh',
    role: 'Professor',
    departmentId: 'prosthodontics',
    department: 'Prosthodontics and crown Bridge',
    qualification: 'MDS (Prosthodontics and Crown & Bridge)',
    experience: '16 years',
    research: 'Full mouth rehabilitation, CAD/CAM prosthetics & implant occlusion.',
    email: 'drmuthuvignesh.j@apdch.edu.in',
    office: 'Prostho Block, Suite 3',
    bio: 'Specializes in clinical prosthodontics, CAD/CAM laboratory workflows, full mouth rehabilitation, and crown & bridge care.',
    image: '/Dr J Muthuvignesh.png',
  },
  {
    id: 'kirubakaran-a',
    name: 'Dr. A. Kirubakaran',
    role: 'Reader',
    departmentId: 'prosthodontics',
    department: 'Prosthodontics and crown Bridge',
    qualification: 'MDS (Prosthodontics and Crown & Bridge)',
    experience: '10 years',
    research: 'Full mouth rehabilitation, CAD/CAM prosthetics & implant occlusion.',
    email: 'drkirubakarana@apdch.edu.in',
    office: 'Prostho Block, Suite 4',
    bio: 'Specializes in clinical prosthodontics, CAD/CAM laboratory workflows, full mouth rehabilitation, and crown & bridge care.',
    image: '/kirubakaran.png',
  },
  {
    id: 'karthik-v-c',
    name: 'Dr. V. C. Karthik',
    role: 'Reader',
    departmentId: 'prosthodontics',
    department: 'Prosthodontics and crown Bridge',
    qualification: 'MDS (Prosthodontics and Crown & Bridge)',
    experience: '8 years',
    research: 'Full mouth rehabilitation, CAD/CAM prosthetics & implant occlusion.',
    email: 'drkarthikvc@apdch.edu.in',
    office: 'Prostho Block, Suite 5',
    bio: 'Specializes in clinical prosthodontics, CAD/CAM laboratory workflows, full mouth rehabilitation, and crown & bridge care.',
    image: '/cv karthik.png',
  },
  {
    id: 'sonia-abraham',
    name: 'Dr. Sonia Abraham',
    role: 'Reader',
    departmentId: 'prosthodontics',
    department: 'Prosthodontics and crown Bridge',
    qualification: 'MDS (Prosthodontics and Crown & Bridge)',
    experience: '8 years',
    research: 'Full mouth rehabilitation, CAD/CAM prosthetics & implant occlusion.',
    email: 'drsoniaabraham@apdch.edu.in',
    office: 'Prostho Block, Suite 6',
    bio: 'Specializes in clinical prosthodontics, CAD/CAM laboratory workflows, full mouth rehabilitation, and crown & bridge care.',
    image: '/sonia.png',
  },
  {
    id: 'vasanthakumari',
    name: 'Dr. A. Vasanthakumari',
    role: 'Professor & HOD',
    departmentId: 'pedodontics',
    department: 'Pedodontics & Preventive Dentistry',
    qualification: 'MDS (Pedodontics & Preventive Dentistry)',
    experience: '22 years',
    research: 'Paediatric behaviour guidance; caries risk models in school cohorts.',
    email: 'vasanthakumari@apdch.edu.in',
    office: 'Pediatric Wing, Room C-01',
    bio: 'Leads paediatric dental services, clinical training, and fear-free child dentistry programs.',
    image: '/Dr.A.Vasanthakumari-Proff-HOD-Dept-of-Pedodontics.png',
  },
  {
    id: 'bharath',
    name: 'Dr. N. Bharath',
    role: 'Associate Professor & HOD In-charge',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry - Endodontics',
    qualification: 'MDS (Conservative Dentistry & Endodontics)',
    experience: '14 years',
    research: 'Aesthetic operative dentistry; endodontic protocols and bonding longevity.',
    email: 'bharath@apdch.edu.in',
    office: 'Cons & Endo, Room E-05',
    bio: 'Leads clinical operative dentistry, rubber dam protocols, micro-endodontic training, and patient care workflows.',
    image: '/bharath .jpg',
  },
  {
    id: 'karthikeyan-s',
    name: 'Dr. S. Karthikeyan',
    role: 'Professor & HOD',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry - Endodontics',
    qualification: 'MDS (Conservative Dentistry & Endodontics)',
    experience: '20 years',
    research: 'Micro-endodontics, aesthetic restorative materials, & rotary endodontics.',
    email: 'karthikeyan.s@apdch.edu.in',
    office: 'Cons & Endo, Room E-01',
    bio: 'Leads the Department of Conservative Dentistry & Endodontics, overseeing advanced micro-endodontics and aesthetic restorative care.',
    image: '/Dr-S-Karthikeyan-MDS.png',
  },
  {
    id: 'sujith-r',
    name: 'Dr. R. Sujith',
    role: 'Associate Professor',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry - Endodontics',
    qualification: 'MDS (Conservative Dentistry & Endodontics)',
    experience: '12 years',
    research: 'Restorative resin composites, root canal disinfection, & endodontic retreatment.',
    email: 'sujith.r@apdch.edu.in',
    office: 'Cons & Endo, Room E-03',
    bio: 'Specializes in aesthetic restorative dentistry, root canal therapy, micro-endodontic retreatment, and preclinical endodontic instruction.',
    image: '/Dr-R-Sujith-MDS.png',
  },
  {
    id: 'sathish-s',
    name: 'Dr. S. Sathish',
    role: 'Senior Lecturer',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry - Endodontics',
    qualification: 'MDS (Conservative Dentistry & Endodontics)',
    experience: '7 years',
    research: 'Endodontic instruments, restorative materials, & canal preparation.',
    email: 'sathish.s@apdch.edu.in',
    office: 'Cons & Endo, Room E-04',
    bio: 'Specializes in root canal treatments, aesthetic composite restorations, and preclinical student guidance.',
    image: '/Dr-S-Sathish-MDS.png',
  },
  {
    id: 'sudhakar-v',
    name: 'Dr. V. Sudhakar',
    role: 'Associate Professor',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry - Endodontics',
    qualification: 'MDS (Conservative Dentistry & Endodontics)',
    experience: '11 years',
    research: 'Restorative materials, endodontic re-treatment, & bonding systems.',
    email: 'sudhakar.v@apdch.edu.in',
    office: 'Cons & Endo, Room E-06',
    bio: 'Specializes in aesthetic restorative procedures, micro-endodontic treatments, and postgraduate clinical instruction.',
    image: '/sudhakar.png',
  },
  {
    id: 'purushothaman-s',
    name: 'Dr. S. Purushothaman',
    role: 'Associate Professor',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry - Endodontics',
    qualification: 'MDS (Conservative Dentistry & Endodontics)',
    experience: '10 years',
    research: 'Canal obturation techniques, bonding resin aesthetics, & rotary instrumentation.',
    email: 'purushothaman.s@apdch.edu.in',
    office: 'Cons & Endo, Room E-07',
    bio: 'Specializes in aesthetic restorative dentistry, endodontic therapy, composite bonding, and clinical instruction.',
    image: '/purusho.png',
  },
  {
    id: 'saranya-s',
    name: 'Dr. S. Saranya',
    role: 'Senior Lecturer',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry - Endodontics',
    qualification: 'MDS (Conservative Dentistry & Endodontics)',
    experience: '6 years',
    research: 'Esthetic dental restorations, vital pulp therapy, & microscopic endodontics.',
    email: 'saranya.s@apdch.edu.in',
    office: 'Cons & Endo, Room E-08',
    bio: 'Specializes in aesthetic restorative dentistry, root canal treatments, and operative clinical training.',
    image: '/saranya.png',
  },
  {
    id: 'visithra-v',
    name: 'Dr. V. Visithra',
    role: 'Senior Lecturer',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry - Endodontics',
    qualification: 'MDS (Conservative Dentistry & Endodontics)',
    experience: '5 years',
    research: 'Restorative materials, endodontic pulp preservation, & canal preparation.',
    email: 'visithra.v@apdch.edu.in',
    office: 'Cons & Endo, Room E-09',
    bio: 'Specializes in aesthetic restorative dentistry, endodontic therapy, and student clinical guidance.',
    image: '/Dr V Visithra.png',
  },
  {
    id: 'raghul-r',
    name: 'Dr. R. Raghul',
    role: 'Senior Lecturer',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry - Endodontics',
    qualification: 'MDS (Conservative Dentistry & Endodontics)',
    experience: '5 years',
    research: 'Restorative resins, root canal obturation, & endodontic disinfection.',
    email: 'raghul.r@apdch.edu.in',
    office: 'Cons & Endo, Room E-10',
    bio: 'Specializes in conservative dentistry, root canal treatments, and clinical patient care.',
    image: '/Dr R Raghul.png',
  },
  {
    id: 'shobiya-s',
    name: 'Dr. S. Shobiya',
    role: 'Senior Lecturer',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry - Endodontics',
    qualification: 'MDS (Conservative Dentistry & Endodontics)',
    experience: '5 years',
    research: 'Operative dentistry, esthetic bonding resins, & canal preparation.',
    email: 'shobiya.s@apdch.edu.in',
    office: 'Cons & Endo, Room E-11',
    bio: 'Specializes in aesthetic restorative dentistry, root canal treatments, and clinical student instruction.',
    image: '/Dr S Shobiya.png',
  },
  {
    id: 'kayalvizhimeena-mg',
    name: 'Dr. M. G. Kayalvizhimeena',
    role: 'Senior Lecturer',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry - Endodontics',
    qualification: 'MDS (Conservative Dentistry & Endodontics)',
    experience: '5 years',
    research: 'Operative aesthetics, micro-endodontic therapy, & canal preparation.',
    email: 'kayalvizhimeena.mg@apdch.edu.in',
    office: 'Cons & Endo, Room E-12',
    bio: 'Specializes in aesthetic composite restorations, root canal treatments, and operative clinical training.',
    image: '/Dr-M-G-Kayalvizhimeena.png',
  },
  {
    id: 'ramkumar-s',
    name: 'Dr. S. Ramkumar',
    role: 'Senior Lecturer',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry - Endodontics',
    qualification: 'MDS (Conservative Dentistry & Endodontics)',
    experience: '5 years',
    research: 'Endodontic obturation, aesthetic composite restorations, & root canal therapy.',
    email: 'ramkumar.s@apdch.edu.in',
    office: 'Cons & Endo, Room E-13',
    bio: 'Specializes in aesthetic restorative procedures, root canal treatments, and clinical student instruction.',
    image: '/Dr S Ramkumar.png',
  },
  {
    id: 'sujitha-m',
    name: 'Dr. M. Sujitha',
    role: 'Senior Lecturer',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry - Endodontics',
    qualification: 'MDS (Conservative Dentistry & Endodontics)',
    experience: '5 years',
    research: 'Esthetic composite restorations, micro-endodontic treatment, & canal preparation.',
    email: 'sujitha.m@apdch.edu.in',
    office: 'Cons & Endo, Room E-14',
    bio: 'Specializes in aesthetic operative dentistry, root canal treatments, and clinical student guidance.',
    image: '/Dr M Sujitha.png',
  },
  {
    id: 'praveen-kumar-c',
    name: 'Dr. C. Praveen Kumar',
    role: 'Senior Lecturer',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry - Endodontics',
    qualification: 'MDS (Conservative Dentistry & Endodontics)',
    experience: '5 years',
    research: 'Esthetic composite restorations, root canal disinfection, & endodontic materials.',
    email: 'praveenkumar.c@apdch.edu.in',
    office: 'Cons & Endo, Room E-15',
    bio: 'Specializes in aesthetic restorative dentistry, root canal treatments, and clinical patient care.',
    image: '/Dr C Praveen Kumar.png',
  },
  {
    id: 'ranganathan',
    name: 'Dr. K. Ranganathan',
    role: 'Professor & HOD',
    departmentId: 'oral-pathology',
    department: 'Oral Pathology',
    qualification: 'MDS (Oral Pathology & Microbiology)',
    experience: '21 years',
    research: 'Histopathological grading, salivary diagnostics, and oral precancer biomarkers.',
    email: 'ranganathan@apdch.edu.in',
    office: 'Histopathology Lab, Block B',
    bio: 'Directs oral histopathology diagnostics, biopsy processing, and postgraduate research in Oral Pathology.',
    image:
      'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=600&q=80&auto=format&fit=crop',
  },
  {
    id: 'sridevi-n',
    name: 'Dr. N. Sridevi',
    role: 'Associate Professor',
    departmentId: 'oral-pathology',
    department: 'Oral Pathology',
    qualification: 'MDS (Oral Pathology)',
    experience: '13 years',
    research: 'Odontogenic cyst immunohistochemistry and microscopic slide archives.',
    email: 'sridevi@apdch.edu.in',
    office: 'Oral Pathology Lab, Room 12',
    bio: 'Leads microscopic pathology labs, forensic odontology workshops, and student diagnostic training.',
    image:
      'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&q=80&auto=format&fit=crop',
  },
  {
    id: 'kalaivani',
    name: 'Dr. S. Kalaivani',
    role: 'Associate Professor & HOD',
    departmentId: 'public-health-dentistry',
    department: 'Public Health Dentistry',
    qualification: 'MDS (Public Health Dentistry)',
    experience: '17 years',
    research: 'Community programme design; caries prevalence mapping & field epidemiology.',
    email: 'kalaivani@apdch.edu.in',
    office: 'Public Health Unit, Desk 1',
    bio: 'Architects district partnerships, community screening camps, school oral health programs, and student outreach.',
    image: '/Dr.-S-Kalaivani.jpg',
  },
  {
    id: 'manjula-krishnan',
    name: 'Dr. Manjula Krishnan',
    role: 'Professor',
    departmentId: 'public-health-dentistry',
    department: 'Public Health Dentistry',
    qualification: 'MDS (Public Health Dentistry)',
    experience: '17 years',
    research: 'Community programme design; caries prevalence mapping.',
    email: 'manjula.krishnan@apdch.edu.in',
    office: 'Public Health Unit, Desk 1',
    bio: 'Architects district partnerships and student-led outreach with rigorous field ethics.',
    image:
      'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=600&q=80&auto=format&fit=crop',
  },
  {
    id: 'ajay-pratap',
    name: 'Dr. Ajay Pratap',
    role: 'Associate Professor',
    departmentId: 'public-health-dentistry',
    department: 'Public Health Dentistry',
    qualification: 'MDS (Public Health Dentistry), MPH',
    experience: '8 years',
    research: 'Epidemiology, biostatistics, and behaviour-change trials.',
    email: 'ajay.pratap@apdch.edu.in',
    office: 'Public Health Unit, Desk 3',
    bio: 'Trains students in survey design and clean data storytelling for community impact.',
    image:
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&q=80&auto=format&fit=crop',
  },
]
