export const PG_STUDENTS_FILTERS = [
  { id: 'conservative-dentistry', label: 'Conservative Dentistry & Endodontics' },
  { id: 'oral-surgery', label: 'Oral & Maxillofacial Surgery' },
  { id: 'orthodontics', label: 'Orthodontics & Dentofacial Orthopaedics' },
  { id: 'prosthodontics', label: 'Prosthodontics & Crown & Bridge' },
  { id: 'periodontics', label: 'Periodontics & Implantology' },
  { id: 'pedodontics', label: 'Pedodontics & Preventive Dentistry' },
  { id: 'oral-pathology', label: 'Oral Pathology' },
]

export const PG_STUDENTS = [
  {
    id: 'pg-1',
    name: 'Dr. M. Abdul Kadir',
    year: '1st Year PG [2025–2026]',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry & Endodontics',
    dissertation: 'Comparative Evaluation of Micro-CT Smear Layer Removal using Rotary vs. Ultrasonic Irrigation.',
    email: 'abdulkadir.pg@apdch.edu.in',
    image: '/abdul.png',
  },
  {
    id: 'pg-2',
    name: 'Dr. D. Dhanasekaran',
    year: '1st Year PG [2025–2026]',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry & Endodontics',
    dissertation: 'Evaluation of Marginal Adaptation of Bioceramic Root Repair Materials in Open Apex Cases.',
    email: 'dhanasekaran.pg@apdch.edu.in',
    image: '/dhana.png',
  },
  {
    id: 'pg-3',
    name: 'Dr. T. Gnana Soundarya',
    year: '1st Year PG [2025–2026]',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry & Endodontics',
    dissertation: 'Fracture Resistance of Endodontically Treated Teeth Restored with Short Fiber-Reinforced Composite.',
    email: 'gnanasoundarya.pg@apdch.edu.in',
    image: '/gana.png',
  },
  {
    id: 'pg-4',
    name: 'Dr. S. S. Nithish Kumar',
    year: '1st Year PG [2025–2026]',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry & Endodontics',
    dissertation: 'Evaluation of 3D Printed Patient-Specific Materials in Endodontics.',
    email: 'nithishkumar.pg@apdch.edu.in',
    image: '/nithish.png',
  },
  {
    id: 'pg-5',
    name: 'Dr. V. Ramya Rajeswari',
    year: '1st Year PG [2025–2026]',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry & Endodontics',
    dissertation: 'Assessment of Root Canal Morphology using High Resolution Imaging.',
    email: 'ramyarajeswari.pg@apdch.edu.in',
    image: '/ramya.png',
  },
  {
    id: 'pg-6',
    name: 'Dr. M. S. Afrose Fathima',
    year: '2nd Year PG [2025–2026]',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry & Endodontics',
    dissertation: 'Comparative Evaluation of Smear Layer Removal using Rotary vs. Ultrasonic Systems.',
    email: 'afrose.pg@apdch.edu.in',
    image: '/afrose.png',
  },
  {
    id: 'pg-7',
    name: 'Dr. R. Dinakar',
    year: '2nd Year PG [2025–2026]',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry & Endodontics',
    dissertation: 'Evaluation of Bioceramic Materials in Endodontics.',
    email: 'dinakar.pg@apdch.edu.in',
    image: '/dinakar.png',
  },
  {
    id: 'pg-8',
    name: 'Dr. C. Harishma Mahalakshmi',
    year: '2nd Year PG [2025–2026]',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry & Endodontics',
    dissertation: 'Assessment of Marginal Adaptation in Endodontically Treated Teeth.',
    email: 'harishma.pg@apdch.edu.in',
    image: '/harishma.png',
  },
  {
    id: 'pg-9',
    name: 'Dr. D. Jeevanandhan',
    year: '2nd Year PG [2025–2026]',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry & Endodontics',
    dissertation: 'Microbial Reduction in Endodontic Infections.',
    email: 'jeevanandhan.pg@apdch.edu.in',
    image: '/jeeva.png',
  },
  {
    id: 'pg-10',
    name: 'Dr. S. Neeralya Nandhini',
    year: '2nd Year PG [2025–2026]',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry & Endodontics',
    dissertation: 'Evaluation of Bioceramic Materials in Endodontics.',
    email: 'neeralyanandhini.pg@apdch.edu.in',
    image: '/neer.png',
  },
  {
    id: 'pg-11',
    name: 'Dr. R. Blessie',
    year: '3rd Year PG [2025–2026]',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry & Endodontics',
    dissertation: 'Evaluation of Bioceramic Materials in Endodontics.',
    email: 'blessie.pg@apdch.edu.in',
    image: '/blessie.png',
  },
  {
    id: 'pg-12',
    name: 'Dr. S. Francy Teena',
    year: '3rd Year PG [2025–2026]',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry & Endodontics',
    dissertation: 'Evaluation of Bioceramic Materials in Endodontics.',
    email: 'francyteena.pg@apdch.edu.in',
    image: '/francy.png',
  },
  {
    id: 'pg-13',
    name: 'Dr. K. Nivetha',
    year: '3rd Year PG [2025–2026]',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry & Endodontics',
    dissertation: 'Evaluation of Bioceramic Materials in Endodontics.',
    email: 'nivetha.pg@apdch.edu.in',
    image: '/nivetha.png',
  },
  {
    id: 'pg-14',
    name: 'Dr. Satyaa Rajesh',
    year: '3rd Year PG [2025–2026]',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry & Endodontics',
    dissertation: 'Evaluation of Bioceramic Materials in Endodontics.',
    email: 'satyaarajesh.pg@apdch.edu.in',
    image: '/dr.sathya.png',
  },
  {
    id: 'pg-15',
    name: 'Dr. S. Sona Sri',
    year: '3rd Year PG [2025–2026]',
    departmentId: 'conservative-dentistry',
    department: 'Conservative Dentistry & Endodontics',
    dissertation: 'Evaluation of Bioceramic Materials in Endodontics.',
    email: 'sonasri.pg@apdch.edu.in',
    image: '/sona.png',
  },
  {
    id: 'pg-16',
    name: 'Dr. Geethan',
    year: '1st Year PG [2025–2026]',
    departmentId: 'oral-surgery',
    department: 'Oral & Maxillofacial Surgery',
    dissertation: 'Evaluation of Patient Specific Implants in Mandibular Surgery.',
    email: 'geethan.pg@apdch.edu.in',
    image: '/geethan.png',
  },
  {
    id: 'pg-17',
    name: 'Dr. Hariharan Murugan',
    year: '1st Year PG [2025–2026]',
    departmentId: 'oral-surgery',
    department: 'Oral & Maxillofacial Surgery',
    dissertation: 'Evaluation of Patient Specific Implants in Mandibular Surgery.',
    email: 'hariharanmurugan.pg@apdch.edu.in',
    image: '/hari.png',
  },
  {
    id: 'pg-18',
    name: 'Dr. K. H. D. Lakshana',
    year: '1st Year PG [2025–2026]',
    departmentId: 'oral-surgery',
    department: 'Oral & Maxillofacial Surgery',
    dissertation: 'Evaluation of Patient Specific Implants in Mandibular Surgery.',
    email: 'khdlakshana.pg@apdch.edu.in',
    image: '/lakshana.png',
  },
  {
    id: 'pg-19',
    name: 'Dr. S. P. Sanjai',
    year: '1st Year PG [2025–2026]',
    departmentId: 'oral-surgery',
    department: 'Oral & Maxillofacial Surgery',
    dissertation: 'Evaluation of Patient Specific Implants in Mandibular Surgery.',
    email: 'sanjai.pg@apdch.edu.in',
    image: '/sanjai.png',
  },
  {
    id: 'pg-20',
    name: 'Dr. S. Varsha',
    year: '1st Year PG [2025–2026]',
    departmentId: 'oral-surgery',
    department: 'Oral & Maxillofacial Surgery',
    dissertation: 'Evaluation of Patient Specific Implants in Mandibular Surgery.',
    email: 'varsha.pg@apdch.edu.in',
    image: '/varsha.png',
  },
  {
    id: 'pg-21',
    name: 'Dr. G. Anbarasan',
    year: '2nd Year PG [2025–2026]',
    departmentId: 'oral-surgery',
    department: 'Oral & Maxillofacial Surgery',
    dissertation: 'Evaluation of Patient Specific Implants in Mandibular Surgery.',
    email: 'anbarasan.pg@apdch.edu.in',
    image: '/anbarasan.png',
  },
  {
    id: 'pg-22',
    name: 'Dr. D. Godwin Clifford',
    year: '2nd Year PG [2025–2026]',
    departmentId: 'oral-surgery',
    department: 'Oral & Maxillofacial Surgery',
    dissertation: 'Evaluation of Patient Specific Implants in Mandibular Surgery.',
    email: 'godwinclifford.pg@apdch.edu.in',
    image: '/godwin.png',
  },
  {
    id: 'pg-23',
    name: 'Dr. R. Hariharan',
    year: '2nd Year PG [2025–2026]',
    departmentId: 'oral-surgery',
    department: 'Oral & Maxillofacial Surgery',
    dissertation: 'Evaluation of Patient Specific Implants in Mandibular Surgery.',
    email: 'rhariharan.pg@apdch.edu.in',
    image: '/rhariharan.png',
  },
  {
    id: 'pg-24',
    name: 'Dr. S. V. Suriya',
    year: '2nd Year PG [2025–2026]',
    departmentId: 'oral-surgery',
    department: 'Oral & Maxillofacial Surgery',
    dissertation: 'Evaluation of Patient Specific Implants in Mandibular Surgery.',
    email: 'svsuriya.pg@apdch.edu.in',
    image: '/suriya.png',
  },
  {
    id: 'pg-25',
    name: 'Dr. Andrew Francis Devotta',
    year: '3rd Year PG [2025–2026]',
    departmentId: 'oral-surgery',
    department: 'Oral & Maxillofacial Surgery',
    dissertation: 'Evaluation of Patient Specific Implants in Mandibular Surgery.',
    email: 'andrewdevotta.pg@apdch.edu.in',
    image: '/devotta.png',
  },
  {
    id: 'pg-26',
    name: 'Dr. S. Divakar',
    year: '3rd Year PG [2025–2026]',
    departmentId: 'oral-surgery',
    department: 'Oral & Maxillofacial Surgery',
    dissertation: 'Evaluation of Patient Specific Implants in Mandibular Surgery.',
    email: 'divakar.pg@apdch.edu.in',
    image: '/divakar.png',
  },
  {
    id: 'pg-27',
    name: 'Dr. N. Jagadeeshwar',
    year: '3rd Year PG [2025–2026]',
    departmentId: 'oral-surgery',
    department: 'Oral & Maxillofacial Surgery',
    dissertation: 'Evaluation of Patient Specific Implants in Mandibular Surgery.',
    email: 'jagadeeshwar.pg@apdch.edu.in',
    image: '/jagadeeshwar.png',
  },
  {
    id: 'pg-28',
    name: 'Dr. S. G. Monika Shamala Prabha',
    year: '3rd Year PG [2025–2026]',
    departmentId: 'oral-surgery',
    department: 'Oral & Maxillofacial Surgery',
    dissertation: 'Evaluation of Patient Specific Implants in Mandibular Surgery.',
    email: 'monikashamala.pg@apdch.edu.in',
    image: '/monika.png',
  },
  {
    id: 'pg-29',
    name: 'Dr. K. V. Sureka',
    year: '3rd Year PG [2025–2026]',
    departmentId: 'oral-surgery',
    department: 'Oral & Maxillofacial Surgery',
    dissertation: 'Evaluation of Patient Specific Implants in Mandibular Surgery.',
    email: 'sureka.pg@apdch.edu.in',
    image: '/sureka.png',
  },
  {
    id: 'pg-30',
    name: 'Dr. A. Ajin',
    year: '1st Year PG [2025–2026]',
    departmentId: 'orthodontics',
    department: 'Orthodontics & Dentofacial Orthopaedics',
    dissertation: 'Evaluation of Clear Aligner Biomechanics and Arch Expansion in Orthodontic Treatment.',
    email: 'ajin.pg@apdch.edu.in',
    image: '/ajin.png',
  },
  {
    id: 'pg-31',
    name: 'Dr. C. Janani Priya',
    year: '1st Year PG [2025–2026]',
    departmentId: 'orthodontics',
    department: 'Orthodontics & Dentofacial Orthopaedics',
    dissertation: 'Evaluation of Clear Aligner Biomechanics and Arch Expansion in Orthodontic Treatment.',
    email: 'jananipriya.pg@apdch.edu.in',
    image: '/jananipriya.png',
  },
  {
    id: 'pg-32',
    name: 'Dr. D. Jasmine Cyndhiya',
    year: '1st Year PG [2025–2026]',
    departmentId: 'orthodontics',
    department: 'Orthodontics & Dentofacial Orthopaedics',
    dissertation: 'Evaluation of Clear Aligner Biomechanics and Arch Expansion in Orthodontic Treatment.',
    email: 'jasminecyndhiya.pg@apdch.edu.in',
    image: '/jasmine.png',
  },
  {
    id: 'pg-33',
    name: 'Dr. R. Trisha',
    year: '1st Year PG [2025–2026]',
    departmentId: 'orthodontics',
    department: 'Orthodontics & Dentofacial Orthopaedics',
    dissertation: 'Evaluation of Clear Aligner Biomechanics and Arch Expansion in Orthodontic Treatment.',
    email: 'trisha.pg@apdch.edu.in',
    image: '/trisha.png',
  },
  {
    id: 'pg-34',
    name: 'Dr. Karthiga Kumaravel',
    year: '1st Year PG [2025–2026]',
    departmentId: 'orthodontics',
    department: 'Orthodontics & Dentofacial Orthopaedics',
    dissertation: 'Evaluation of Clear Aligner Biomechanics and Arch Expansion in Orthodontic Treatment.',
    email: 'karthigakumaravel.pg@apdch.edu.in',
    image: '/karthigakumaravel.png',
  },
  {
    id: 'pg-35',
    name: 'Dr. K. Govarthnesan',
    year: '2nd Year PG [2025–2026]',
    departmentId: 'orthodontics',
    department: 'Orthodontics & Dentofacial Orthopaedics',
    dissertation: 'Evaluation of Clear Aligner Biomechanics and Arch Expansion in Orthodontic Treatment.',
    email: 'govarthnesan.pg@apdch.edu.in',
    image: '/govarthnesan.png',
  },
  {
    id: 'pg-36',
    name: 'Dr. K. Lisha',
    year: '2nd Year PG [2025–2026]',
    departmentId: 'orthodontics',
    department: 'Orthodontics & Dentofacial Orthopaedics',
    dissertation: 'Evaluation of Clear Aligner Biomechanics and Arch Expansion in Orthodontic Treatment.',
    email: 'lisha.pg@apdch.edu.in',
    image: '/lisha.png',
  },
  {
    id: 'pg-37',
    name: 'Dr. R. Pavithra',
    year: '2nd Year PG [2025–2026]',
    departmentId: 'orthodontics',
    department: 'Orthodontics & Dentofacial Orthopaedics',
    dissertation: 'Evaluation of Clear Aligner Biomechanics and Arch Expansion in Orthodontic Treatment.',
    email: 'rpavithra.pg@apdch.edu.in',
    image: '/rpavithra.png',
  },
  {
    id: 'pg-38',
    name: 'Dr. S. Priya',
    year: '2nd Year PG [2025–2026]',
    departmentId: 'orthodontics',
    department: 'Orthodontics & Dentofacial Orthopaedics',
    dissertation: 'Evaluation of Clear Aligner Biomechanics and Arch Expansion in Orthodontic Treatment.',
    email: 'spriya.pg@apdch.edu.in',
    image: '/spriya.png',
  },
  {
    id: 'pg-39',
    name: 'Dr. S. Rajalingam',
    year: '2nd Year PG [2025–2026]',
    departmentId: 'orthodontics',
    department: 'Orthodontics & Dentofacial Orthopaedics',
    dissertation: 'Evaluation of Clear Aligner Biomechanics and Arch Expansion in Orthodontic Treatment.',
    email: 'rajalingam.pg@apdch.edu.in',
    image: '/rajalingam.png',
  },
  {
    id: 'pg-40',
    name: 'Dr. R. C. Abinaya',
    year: '3rd Year PG [2025–2026]',
    departmentId: 'orthodontics',
    department: 'Orthodontics & Dentofacial Orthopaedics',
    dissertation: 'Evaluation of Clear Aligner Biomechanics and Arch Expansion in Orthodontic Treatment.',
    email: 'abinaya.pg@apdch.edu.in',
    image: '/abinaya.png',
  },
  {
    id: 'pg-41',
    name: 'Dr. K. Devadharshini',
    year: '3rd Year PG [2025–2026]',
    departmentId: 'orthodontics',
    department: 'Orthodontics & Dentofacial Orthopaedics',
    dissertation: 'Evaluation of Clear Aligner Biomechanics and Arch Expansion in Orthodontic Treatment.',
    email: 'devadharshini.pg@apdch.edu.in',
    image: '/devadharshini.png',
  },
  {
    id: 'pg-42',
    name: 'Dr. N. Mohamed Rahmankhan',
    year: '3rd Year PG [2025–2026]',
    departmentId: 'orthodontics',
    department: 'Orthodontics & Dentofacial Orthopaedics',
    dissertation: 'Evaluation of Clear Aligner Biomechanics and Arch Expansion in Orthodontic Treatment.',
    email: 'rahmankhan.pg@apdch.edu.in',
    image: '/rahmankhan.png',
  },
  {
    id: 'pg-43',
    name: 'Dr. R. Parvathy Kurup',
    year: '3rd Year PG [2025–2026]',
    departmentId: 'orthodontics',
    department: 'Orthodontics & Dentofacial Orthopaedics',
    dissertation: 'Evaluation of Clear Aligner Biomechanics and Arch Expansion in Orthodontic Treatment.',
    email: 'parvathy.pg@apdch.edu.in',
    image: '/parvathy.png',
  },
  {
    id: 'pg-44',
    name: 'Dr. R. Santha Kumari',
    year: '3rd Year PG [2025–2026]',
    departmentId: 'orthodontics',
    department: 'Orthodontics & Dentofacial Orthopaedics',
    dissertation: 'Evaluation of Clear Aligner Biomechanics and Arch Expansion in Orthodontic Treatment.',
    email: 'santhakumari.pg@apdch.edu.in',
    image: '/santhakumari.png',
  },
  {
    id: 'pg-45',
    name: 'Dr. P. Deviya Bharathi',
    year: '1st Year PG [2025–2026]',
    departmentId: 'prosthodontics',
    department: 'Prosthodontics & Crown & Bridge',
    dissertation: 'Evaluation of Fit and Marginal Accuracy of Zirconia Restorations in Prosthodontics.',
    email: 'deviyabharathi.pg@apdch.edu.in',
    image: '/deviyabharathi.png',
  },
  {
    id: 'pg-46',
    name: 'Dr. B. Priyadharshini',
    year: '1st Year PG [2025–2026]',
    departmentId: 'prosthodontics',
    department: 'Prosthodontics & Crown & Bridge',
    dissertation: 'Evaluation of Fit and Marginal Accuracy of Zirconia Restorations in Prosthodontics.',
    email: 'bpriyadharshini.pg@apdch.edu.in',
    image: '/bpriyadharshini.png',
  },
  {
    id: 'pg-47',
    name: 'Dr. A. Sivadharsini',
    year: '1st Year PG [2025–2026]',
    departmentId: 'prosthodontics',
    department: 'Prosthodontics & Crown & Bridge',
    dissertation: 'Evaluation of Fit and Marginal Accuracy of Zirconia Restorations in Prosthodontics.',
    email: 'sivadharsini.pg@apdch.edu.in',
    image: '/sivadharsini.png',
  },
  {
    id: 'pg-48',
    name: 'Dr. B. Vishnu',
    year: '1st Year PG [2025–2026]',
    departmentId: 'prosthodontics',
    department: 'Prosthodontics & Crown & Bridge',
    dissertation: 'Evaluation of Fit and Marginal Accuracy of Zirconia Restorations in Prosthodontics.',
    email: 'bvishnu.pg@apdch.edu.in',
    image: '/bvishnu.png',
  },
  {
    id: 'pg-49',
    name: 'Dr. M. Yazhini',
    year: '1st Year PG [2025–2026]',
    departmentId: 'prosthodontics',
    department: 'Prosthodontics & Crown & Bridge',
    dissertation: 'Evaluation of Fit and Marginal Accuracy of Zirconia Restorations in Prosthodontics.',
    email: 'yazhini.pg@apdch.edu.in',
    image: '/Dr-M-Yazhini.png',
  },
  {
    id: 'pg-50',
    name: 'Dr. K. B. Ajay',
    year: '2nd Year PG [2025–2026]',
    departmentId: 'prosthodontics',
    department: 'Prosthodontics & Crown & Bridge',
    dissertation: 'Evaluation of Fit and Marginal Accuracy of Zirconia Restorations in Prosthodontics.',
    email: 'kbajay.pg@apdch.edu.in',
    image: '/Dr-K-B-Ajay.png',
  },
  {
    id: 'pg-51',
    name: 'Dr. K. B. Elakiya Jyothi',
    year: '2nd Year PG [2025–2026]',
    departmentId: 'prosthodontics',
    department: 'Prosthodontics & Crown & Bridge',
    dissertation: 'Evaluation of Fit and Marginal Accuracy of Zirconia Restorations in Prosthodontics.',
    email: 'elakiyajyothi.pg@apdch.edu.in',
    image: '/Dr-K-B-Elakiya-Jyothi.png',
  },
  {
    id: 'pg-52',
    name: 'Dr. S. Nadi Soundarya',
    year: '2nd Year PG [2025–2026]',
    departmentId: 'prosthodontics',
    department: 'Prosthodontics & Crown & Bridge',
    dissertation: 'Evaluation of Fit and Marginal Accuracy of Zirconia Restorations in Prosthodontics.',
    email: 'nadisoundarya.pg@apdch.edu.in',
    image: '/Dr-S-Nadi-Soundarya.png',
  },
  {
    id: 'pg-53',
    name: 'Dr. S. Rajashree',
    year: '2nd Year PG [2025–2026]',
    departmentId: 'prosthodontics',
    department: 'Prosthodontics & Crown & Bridge',
    dissertation: 'Evaluation of Fit and Marginal Accuracy of Zirconia Restorations in Prosthodontics.',
    email: 'srajashree.pg@apdch.edu.in',
    image: '/Dr-S-Rajashree.png',
  },
  {
    id: 'pg-54',
    name: 'Dr. K. Subashini',
    year: '2nd Year PG [2025–2026]',
    departmentId: 'prosthodontics',
    department: 'Prosthodontics & Crown & Bridge',
    dissertation: 'Evaluation of Fit and Marginal Accuracy of Zirconia Restorations in Prosthodontics.',
    email: 'ksubashini.pg@apdch.edu.in',
    image: '/Dr-K-Subashini.png',
  },
  {
    id: 'pg-55',
    name: 'Dr. J. Jaisan Samraj',
    year: '3rd Year PG [2025–2026]',
    departmentId: 'prosthodontics',
    department: 'Prosthodontics & Crown & Bridge',
    dissertation: 'Evaluation of Fit and Marginal Accuracy of Zirconia Restorations in Prosthodontics.',
    email: 'jaisansamraj.pg@apdch.edu.in',
    image: '/Dr-J-Jaisan-Samraj.png',
  },
  {
    id: 'pg-56',
    name: 'Dr. J. Keerthivasan',
    year: '3rd Year PG [2025–2026]',
    departmentId: 'prosthodontics',
    department: 'Prosthodontics & Crown & Bridge',
    dissertation: 'Evaluation of Fit and Marginal Accuracy of Zirconia Restorations in Prosthodontics.',
    email: 'jkeerthivasan.pg@apdch.edu.in',
    image: '/keerthivasan-pg.png',
  },
  {
    id: 'pg-57',
    name: 'Dr. P. Kiran',
    year: '3rd Year PG [2025–2026]',
    departmentId: 'prosthodontics',
    department: 'Prosthodontics & Crown & Bridge',
    dissertation: 'Evaluation of Fit and Marginal Accuracy of Zirconia Restorations in Prosthodontics.',
    email: 'pkiran.pg@apdch.edu.in',
    image: '/Dr-P-Kiran.png',
  },
  {
    id: 'pg-58',
    name: 'Dr. C. Nethra',
    year: '3rd Year PG [2025–2026]',
    departmentId: 'prosthodontics',
    department: 'Prosthodontics & Crown & Bridge',
    dissertation: 'Evaluation of Fit and Marginal Accuracy of Zirconia Restorations in Prosthodontics.',
    email: 'cnethra.pg@apdch.edu.in',
    image: '/Dr-C-Nethra.png',
  },
  {
    id: 'pg-59',
    name: 'Dr. R. Sedhunarayanan',
    year: '3rd Year PG [2025–2026]',
    departmentId: 'prosthodontics',
    department: 'Prosthodontics & Crown & Bridge',
    dissertation: 'Evaluation of Fit and Marginal Accuracy of Zirconia Restorations in Prosthodontics.',
    email: 'rsedhunarayanan.pg@apdch.edu.in',
    image: '/Dr-R-Sedhunarayanan.png',
  },
  {
    id: 'pg-60',
    name: 'Dr. M. Arumathi',
    year: '1st Year PG [2025–2026]',
    departmentId: 'periodontics',
    department: 'Periodontics & Implantology',
    dissertation: 'Clinical evaluation of contemporary periodontal and implant therapy protocols.',
    email: 'marumathi.pg@apdch.edu.in',
    image: '/Dr-M-Arumathi.png',
  },
  {
    id: 'pg-61',
    name: 'Dr. K. Gayathiri Devi',
    year: '1st Year PG [2025–2026]',
    departmentId: 'periodontics',
    department: 'Periodontics & Implantology',
    dissertation: 'Clinical evaluation of contemporary periodontal and implant therapy protocols.',
    email: 'kgayathiridevi.pg@apdch.edu.in',
    image: '/Dr-K-Gayathiri-Devi.png',
  },
  {
    id: 'pg-62',
    name: 'Dr. K. A. Govartheni',
    year: '1st Year PG [2025–2026]',
    departmentId: 'periodontics',
    department: 'Periodontics & Implantology',
    dissertation: 'Clinical evaluation of contemporary periodontal and implant therapy protocols.',
    email: 'kagovartheni.pg@apdch.edu.in',
    image: '/Dr-K-A-Govartheni.png',
  },
  {
    id: 'pg-63',
    name: 'Dr. R. Premy',
    year: '1st Year PG [2025–2026]',
    departmentId: 'periodontics',
    department: 'Periodontics & Implantology',
    dissertation: 'Clinical evaluation of contemporary periodontal and implant therapy protocols.',
    email: 'rpremy.pg@apdch.edu.in',
    image: '/Dr-R-Premy.png',
  },
  {
    id: 'pg-64',
    name: 'Dr. Shoumiya Preethy Prabakar',
    year: '2nd Year PG [2025–2026]',
    departmentId: 'periodontics',
    department: 'Periodontics & Implantology',
    dissertation: 'Clinical evaluation of contemporary periodontal and implant therapy protocols.',
    email: 'shoumiyapreethy.pg@apdch.edu.in',
    image: '/Dr-Shoumiya-Preethy-Prabakar.png',
  },
  {
    id: 'pg-65',
    name: 'Dr. S. Aarthy',
    year: '2nd Year PG [2025–2026]',
    departmentId: 'periodontics',
    department: 'Periodontics & Implantology',
    dissertation: 'Clinical evaluation of contemporary periodontal and implant therapy protocols.',
    email: 'saarthy.pg@apdch.edu.in',
    image: '/Dr-S-Aarthy.png',
  },
  {
    id: 'pg-66',
    name: 'Dr. D. Angel Fastina Mary',
    year: '2nd Year PG [2025–2026]',
    departmentId: 'periodontics',
    department: 'Periodontics & Implantology',
    dissertation: 'Clinical evaluation of contemporary periodontal and implant therapy protocols.',
    email: 'angelfastinamary.pg@apdch.edu.in',
    image: '/Dr-D-Angel-Fastina-Mary.png',
  },
  {
    id: 'pg-67',
    name: 'Dr. K. Pragathi',
    year: '2nd Year PG [2025–2026]',
    departmentId: 'periodontics',
    department: 'Periodontics & Implantology',
    dissertation: 'Clinical evaluation of contemporary periodontal and implant therapy protocols.',
    email: 'kpragathi.pg@apdch.edu.in',
    image: '/Dr-K-Pragathi.png',
  },
  {
    id: 'pg-68',
    name: 'Dr. D. Roshna',
    year: '2nd Year PG [2025–2026]',
    departmentId: 'periodontics',
    department: 'Periodontics & Implantology',
    dissertation: 'Clinical evaluation of contemporary periodontal and implant therapy protocols.',
    email: 'droshna.pg@apdch.edu.in',
    image: '/Dr-D-Roshna.png',
  },
  {
    id: 'pg-69',
    name: 'Dr. S. Sarmatha',
    year: '2nd Year PG [2025–2026]',
    departmentId: 'periodontics',
    department: 'Periodontics & Implantology',
    dissertation: 'Clinical evaluation of contemporary periodontal and implant therapy protocols.',
    email: 'ssarmatha.pg@apdch.edu.in',
    image: '/Dr-S-Sarmatha.png',
  },
  {
    id: 'pg-70',
    name: 'Dr. K. Deepikashree',
    year: '3rd Year PG [2025–2026]',
    departmentId: 'periodontics',
    department: 'Periodontics & Implantology',
    dissertation: 'Clinical evaluation of contemporary periodontal and implant therapy protocols.',
    email: 'kdeepikashree.pg@apdch.edu.in',
    image: '/Dr-K-Deepikashree.png',
  },
  {
    id: 'pg-71',
    name: 'Dr. V. Ramya',
    year: '3rd Year PG [2025–2026]',
    departmentId: 'periodontics',
    department: 'Periodontics & Implantology',
    dissertation: 'Clinical evaluation of contemporary periodontal and implant therapy protocols.',
    email: 'vramya.pg@apdch.edu.in',
    image: '/Dr-V-Ramya.png',
  },
  {
    id: 'pg-72',
    name: 'Dr. S. Soundarya',
    year: '3rd Year PG [2025–2026]',
    departmentId: 'periodontics',
    department: 'Periodontics & Implantology',
    dissertation: 'Clinical evaluation of contemporary periodontal and implant therapy protocols.',
    email: 'ssoundarya.pg@apdch.edu.in',
    image: '/Dr-S-Soundarya.png',
  },
  {
    id: 'pg-73',
    name: 'Dr. M. D. Tamil Selvan',
    year: '3rd Year PG [2025–2026]',
    departmentId: 'periodontics',
    department: 'Periodontics & Implantology',
    dissertation: 'Clinical evaluation of contemporary periodontal and implant therapy protocols.',
    email: 'mdtamilselvan.pg@apdch.edu.in',
    image: '/Dr-M-D-Tamil-Selvan.png',
  },
  {
    id: 'pg-74',
    name: 'Dr. J. Aravind Rajesh',
    year: '1st Year PG [2025–2026]',
    departmentId: 'pedodontics',
    department: 'Pedodontics & Preventive Dentistry',
    dissertation: 'Clinical evaluation of contemporary pediatric and preventive dentistry protocols.',
    email: 'jaravindrajesh.pg@apdch.edu.in',
    image: '/Dr-J-Aravind-Rajesh.png',
  },
  {
    id: 'pg-75',
    name: 'Dr. Y. Charulekha',
    year: '1st Year PG [2025–2026]',
    departmentId: 'pedodontics',
    department: 'Pedodontics & Preventive Dentistry',
    dissertation: 'Clinical evaluation of contemporary pediatric and preventive dentistry protocols.',
    email: 'ycharulekha.pg@apdch.edu.in',
    image: '/Dr-Y-Charulekha.png',
  },
  {
    id: 'pg-76',
    name: 'Dr. M. Sangheswari',
    year: '1st Year PG [2025–2026]',
    departmentId: 'pedodontics',
    department: 'Pedodontics & Preventive Dentistry',
    dissertation: 'Clinical evaluation of contemporary pediatric and preventive dentistry protocols.',
    email: 'msangheswari.pg@apdch.edu.in',
    image: '/Dr-M-Sangheswari.png',
  },
  {
    id: 'pg-77',
    name: 'Dr. P. Elanchezhiyan',
    year: '2nd Year PG [2025–2026]',
    departmentId: 'pedodontics',
    department: 'Pedodontics & Preventive Dentistry',
    dissertation: 'Clinical evaluation of contemporary pediatric and preventive dentistry protocols.',
    email: 'pelanchezhiyan.pg@apdch.edu.in',
    image: '/Dr-P-Elanchezhiyan.png',
  },
  {
    id: 'pg-78',
    name: 'Dr. R. J. Renishka',
    year: '2nd Year PG [2025–2026]',
    departmentId: 'pedodontics',
    department: 'Pedodontics & Preventive Dentistry',
    dissertation: 'Clinical evaluation of contemporary pediatric and preventive dentistry protocols.',
    email: 'rjrenishka.pg@apdch.edu.in',
    image: '/Dr-R-J-Renishka.png',
  },
  {
    id: 'pg-79',
    name: 'Dr. V. Keerthana',
    year: '3rd Year PG [2025–2026]',
    departmentId: 'pedodontics',
    department: 'Pedodontics & Preventive Dentistry',
    dissertation: 'Clinical evaluation of contemporary pediatric and preventive dentistry protocols.',
    email: 'vkeerthana.pg@apdch.edu.in',
    image: '/Dr-V-Keerthana.png',
  },
  {
    id: 'pg-80',
    name: 'Dr. R. Madhumathy',
    year: '3rd Year PG [2025–2026]',
    departmentId: 'pedodontics',
    department: 'Pedodontics & Preventive Dentistry',
    dissertation: 'Clinical evaluation of contemporary pediatric and preventive dentistry protocols.',
    email: 'rmadhumathy.pg@apdch.edu.in',
    image: '/Dr-R-Madhumathy.png',
  },
  {
    id: 'pg-81',
    name: 'Dr. K. L. Mohana Sriram',
    year: '3rd Year PG [2025–2026]',
    departmentId: 'pedodontics',
    department: 'Pedodontics & Preventive Dentistry',
    dissertation: 'Clinical evaluation of contemporary pediatric and preventive dentistry protocols.',
    email: 'klmohanasriram.pg@apdch.edu.in',
    image: '/Dr-K-L-Mohana-Sriram.png',
  },
  {
    id: 'pg-82',
    name: 'Dr. J. Lincy Jenisha',
    year: '1st Year PG [2025–2026]',
    departmentId: 'oral-pathology',
    department: 'Oral Pathology & Microbiology',
    dissertation: 'Histopathological and molecular evaluation of contemporary oral disease markers.',
    email: 'jlincyjenisha.pg@apdch.edu.in',
    image: '/Dr-J-Lincy-Jenisha.png',
  },
  {
    id: 'pg-83',
    name: 'Dr. A. Nandhini',
    year: '1st Year PG [2025–2026]',
    departmentId: 'oral-pathology',
    department: 'Oral Pathology & Microbiology',
    dissertation: 'Histopathological and molecular evaluation of contemporary oral disease markers.',
    email: 'anandhini.pg@apdch.edu.in',
    image: '/Dr-A-Nandhini.png',
  },
  {
    id: 'pg-84',
    name: 'Dr. P. Shinola Jeniffer',
    year: '2nd Year PG [2025–2026]',
    departmentId: 'oral-pathology',
    department: 'Oral Pathology & Microbiology',
    dissertation: 'Histopathological and molecular evaluation of contemporary oral disease markers.',
    email: 'pshinolajeniffer.pg@apdch.edu.in',
    image: '/Dr-P-Shinola-Jeniffer.png',
  },
  {
    id: 'pg-85',
    name: 'Dr. M. Srinath',
    year: '3rd Year PG [2025–2026]',
    departmentId: 'oral-pathology',
    department: 'Oral Pathology & Microbiology',
    dissertation: 'Histopathological and molecular evaluation of contemporary oral disease markers.',
    email: 'msrinath.pg@apdch.edu.in',
    image: '/Dr-M-Srinath.png',
  },
  {
    id: 'pg-86',
    name: 'Dr. S. R. Swetha',
    year: '3rd Year PG [2025–2026]',
    departmentId: 'oral-pathology',
    department: 'Oral Pathology & Microbiology',
    dissertation: 'Histopathological and molecular evaluation of contemporary oral disease markers.',
    email: 'srswetha.pg@apdch.edu.in',
    image: '/Dr-S-R-Swetha.png',
  },
]
